### ISSUE TITLE
Migrate Code to OpenSearch Github account

### ISSUE THREAD

**Issue by epugh** [o19s/opensearch-ubi#84]

**Comment by jzonthemtn** [comment]
This includes other projects under the o19s organization in addition to this project.

**Comment by jzonthemtn** [comment]
We learned that moving the projects over to the opensearch organization will be a lengthy process. We can create an issue in the OpenSearch project to start the process, but it will take time. For the immediate future, we will create releases from our repository.

The action item from this issue is to create an issue in the OpenSearch organization to start the process of moving the repositories.

**Comment by epugh** [comment]
For now, we live under the `com.o19s` domain.
